{% set name = "deepinv" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepinv/deepinv/archive/refs/tags/v.{{ version }}.tar.gz
  sha256: 3e040ff13ba5f6967454a4c53ad495839c1eb48bf743f700b64b72f5cc199e72

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - hdf5storage
    - tqdm
    - pytorch
    - torchvision
    - torchmetrics
    - einops
    - wandb
    - scipy

test:
  imports:
    - deepinv
  commands:
    - pip check
    - pytest deepinv/tests -vs
  source_files:
    - deepinv/tests/*
    - deepinv/tests/assets/generators/*
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - datasets
    - ipython

about:
  summary: Pytorch library for solving inverse problems with deep learning
  dev_url: https://github.com/deepinv/deepinv
  home: https://github.com/deepinv/deepinv
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gschramm
    - tachella
    - matthieutrs
