{% set name = "deepinv" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepinv/deepinv/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ba572b4a1a49b4b46b0f11b82201ba8c8391d0fbef24355649acc0b363dba939

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - hdf5storage
    - tqdm
    - pytorch <2.7
    - torchvision
    - torchmetrics
    - einops
    - wandb
    - scipy
    - natsort

test:
  imports:
    - deepinv
  commands:
    - pip check
    - pytest deepinv/tests -v -k "not test_ncsnpp_net" -k "test_algo_inpaint and not DDRM"
  source_files:
    - deepinv/tests/*
    - deepinv/tests/assets/generators/*
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - datasets
    - ipython
    - timm
    - pywavelets
    - kornia
    - torchkbnufft
    - sigpy
    - mat73

about:
  summary: Pytorch library for solving inverse problems with deep learning
  dev_url: https://github.com/deepinv/deepinv
  home: https://github.com/deepinv/deepinv
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gschramm
    - tachella
    - matthieutrs
