{% set name = "deepinv" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepinv-{{ version }}.tar.gz
  sha256: 87c6dfb737a2fb0834f395521287f0095ee7fbede906cae258ca691a84bcad3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - pip
  run:
    - python >=3.8
    - numpy
    - matplotlib-base
    - hdf5storage
    - tqdm
    - pytorch
    - torchvision
    - einops
    - wandb

test:
  imports:
    - deepinv
  commands:
    - pip check
    - pytest deepinv/tests -vs
  source_files:
    - deepinv/tests/*
  requires:
    - pip
    - pytest

about:
  summary: Pytorch library for solving inverse problems with deep learning
  dev_url: https://github.com/deepinv/deepinv
  home: https://github.com/deepinv/deepinv
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gschramm
    - tachella
    - matthieutrs
